# Experiment parameters
experiment_name: "test_experiment"
run_name: "test_run"
# Environment parameters
min_task_size: 4
max_task_size: 4
min_num_tasks: 12
max_num_tasks: 12
min_node_size: 12
max_node_size: 12
min_num_nodes: 8
max_num_nodes: 8
number_of_critical_tasks: 3
number_of_replicas: 2
min_num_comms: 10
max_num_comms: 10
max_comm_chain: 3
non_critical_comm: true
critical_comm: true
use_comm_graph_in_train: true
invalid_action_replacement: false
# Reward parameters
SUCCESS_reward: 10
DUPLICATE_PICK_reward: -1
NODE_OVERFLOW_reward: -2
STEP_reward: 1
BONUS_reward: 0.25
CRITICAL_reward: 1
DUPLICATE_CRITICAL_PICK_reward: -1
COMM_reward: 10
# NODE_OCCUPANCY_reward: 0
# MESSAGE_CHANNEL_OCCUPANCY_reward: 0
# Model parameters
seed: 3
eval_seed: 42
epochs: 1000
eval_timesteps: 10000
batch_size: 64
lr: 0.0003
alpha: 0.3
device: "cuda:3"
train: true
inference: true
verbose: false
model_path: ""